// @ts-check

export const MEDIA_COPY = {
  en: {
    heading: 'Viewing history',
    allServices: 'All services',
    provider: 'Service',
    timezone: 'Display timezone',
    titleFilter: 'Find a title',
    exportCombined: 'Export filtered CSV',
    profileLabel: 'Profile label',
    sourceCoverage: 'Source coverage',
    seconds: 'Recorded seconds',
    watchTime: 'Recorded watch time',
    unknownDuration: 'Records with unknown duration',
    exclusions: 'Excluded from consumption totals',
    searches: 'Searches',
    purchases: 'Purchases',
    rentals: 'Rentals',
    devices: 'Devices',
    audioLanguages: 'Audio languages',
    subtitleLanguages: 'Subtitle languages',
    unsupported: 'Unsupported files',
    datasets: 'Datasets',
    playbackDetails: 'Playback details',
    watchEvents: 'Supplementary watch events',
    trailers: 'Promotional trailers',
    sourceFile: 'Source file',
    sourceRow: 'Source row',
    unit: 'Counting unit',
    netflixUnit: 'Activity entries',
    primeUnit: 'Playback records',
    profileType: 'Profile type',
    completion: 'Completion',
    autoplay: 'Autoplay',
    deleted: 'Deleted from history',
    yes: 'Yes',
    no: 'No',
    sourceNote:
      'Totals combine Netflix activity entries and Prime content playback with positive recorded seconds. Each service keeps its counting unit.',
    watchNote:
      'Supplementary Watch Events, searches, purchases, trailers, promotions, deleted records, and zero or unknown durations stay outside consumption totals.',
    timeNote:
      'Prime timestamps use the selected timezone. Netflix calendar dates remain unchanged.',
    profileNote:
      'Prime supplies adult and child profile types, without individual profile identifiers.',
    runtimeNote:
      'Metadata runtime describes the title. Recorded seconds describe playback. Completion remains unknown.',
    titleNote:
      'Only accepted title identities join across services. Unresolved titles keep their service identity.',
    empty: 'Import your history to build this report.',
    confirmDeletePrime: 'Delete Prime Video data',
    deletePrimeTitle: 'Delete all Prime Video data?',
    deletePrimeBody:
      'This removes Prime source records, previews, and title results from your private workspace.',
    primeGuide: 'Amazon export guide',
    next: 'Next page',
    previous: 'Previous page',
    interval: 'Playback interval',
    content: 'Content',
    promotion: 'Promotion',
    trailer: 'Trailer',
    live: 'Live',
    adult: 'Adult',
    child: 'Child',
    calendarDate: 'Calendar date',
    timestamp: 'UTC timestamp',
    unknownTitle: 'Title unavailable',
    playbackEvidence: 'Purchase records with playback evidence',
    recordedCoverage: 'Consumption records with recorded seconds',
    episodeNote:
      'Episode counts use distinct source identities within each service. A series match joins series history and leaves episode identity unconfirmed.',
    coverageNote:
      'Source coverage shows all selected datasets. Preview dates use UTC. Report dates use the display timezone.',
    weekdayActivity: 'Activity by weekday',
    chartEmpty: 'No data is available for this chart.',
    addFiles: 'Add files',
    uploadTitle: 'Upload your viewing history',
    uploadHint: 'Netflix CSV or Prime Video ZIP',
    close: 'Close',
    manageFiles: 'Manage files',
    analyzing: 'Analyzing your history…',
    analysisFailed:
      'Analysis could not finish. Retry or cancel the pending analysis.',
    importFailed:
      'The file could not be imported. Cancel the pending import, then select the file again.',
    history: 'History',
    filters: 'Report filters',
    moreFilters: 'More filters',
    allTitles: 'All titles',
    films: 'Films',
    mediaSplit: 'Films & series',
    monthlyViewing: 'Monthly viewing activity',
    topGenres: 'Most watched genres',
    weekdayGenres: 'Genres by weekday',
    originalLanguages: 'Original languages',
    originalLanguageNote: 'The title’s original language.',
    yearGenres: 'Genres over the years',
    genreOverlap: 'Activities can belong to more than one genre.',
    filteredPeriods:
      'Counts cover the selected dates, including partial years.',
    weekday: 'Weekday',
    viewingYear: 'Viewing year',
    month: 'Month',
    replaceFile: 'Replace file',
    deleteData: 'Delete data',
    deleteBody:
      'This removes the selected service’s imported history and title details.',
    aboutReport: 'About this report',
    netflixGuide: 'Netflix export guide',
    invalidFiles: 'Choose one Netflix CSV and one Prime Video ZIP at most.'
  },
  es: {
    heading: 'Historial de visualización',
    allServices: 'Todos los servicios',
    provider: 'Servicio',
    timezone: 'Zona horaria',
    titleFilter: 'Buscar un título',
    exportCombined: 'Exportar CSV filtrado',
    profileLabel: 'Nombre del perfil',
    sourceCoverage: 'Cobertura de fuentes',
    seconds: 'Segundos registrados',
    watchTime: 'Tiempo de reproducción registrado',
    unknownDuration: 'Registros sin duración conocida',
    exclusions: 'Excluidos del total de consumo',
    searches: 'Búsquedas',
    purchases: 'Compras',
    rentals: 'Alquileres',
    devices: 'Dispositivos',
    audioLanguages: 'Idiomas de audio',
    subtitleLanguages: 'Idiomas de subtítulos',
    unsupported: 'Archivos no admitidos',
    datasets: 'Conjuntos de datos',
    playbackDetails: 'Detalles de reproducción',
    watchEvents: 'Eventos de reproducción complementarios',
    trailers: 'Tráilers promocionales',
    sourceFile: 'Archivo de origen',
    sourceRow: 'Fila de origen',
    unit: 'Unidad de recuento',
    netflixUnit: 'Entradas de actividad',
    primeUnit: 'Registros de reproducción',
    profileType: 'Tipo de perfil',
    completion: 'Finalización',
    autoplay: 'Reproducción automática',
    deleted: 'Eliminado del historial',
    yes: 'Sí',
    no: 'No',
    sourceNote:
      'Los totales combinan entradas de Netflix y reproducciones de contenido Prime con segundos positivos. Cada servicio conserva su unidad.',
    watchNote:
      'Los eventos complementarios, búsquedas, compras, tráilers, promociones, registros eliminados y duraciones cero o desconocidas quedan fuera del total.',
    timeNote:
      'Las marcas de Prime usan la zona seleccionada. Las fechas de Netflix no cambian.',
    profileNote:
      'Prime indica perfiles de adultos o niños, sin identificadores de perfiles individuales.',
    runtimeNote:
      'La duración de los metadatos describe el título. Los segundos registrados describen la reproducción. La finalización es desconocida.',
    titleNote:
      'Solo las identidades aceptadas unen títulos entre servicios. Los títulos sin resolver conservan su identidad de servicio.',
    empty: 'Importa tu historial para crear este informe.',
    confirmDeletePrime: 'Eliminar datos de Prime Video',
    deletePrimeTitle: '¿Eliminar todos los datos de Prime Video?',
    deletePrimeBody:
      'Se eliminarán los registros, vistas previas y resultados de títulos de Prime de tu espacio privado.',
    primeGuide: 'Guía de exportación de Amazon',
    next: 'Página siguiente',
    previous: 'Página anterior',
    interval: 'Intervalo de reproducción',
    content: 'Contenido',
    promotion: 'Promoción',
    trailer: 'Tráiler',
    live: 'En directo',
    adult: 'Adulto',
    child: 'Niño',
    calendarDate: 'Fecha de calendario',
    timestamp: 'Marca de tiempo UTC',
    unknownTitle: 'Título no disponible',
    playbackEvidence: 'Compras con evidencia de reproducción',
    recordedCoverage: 'Registros de consumo con segundos registrados',
    episodeNote:
      'Los episodios se cuentan por identidades de origen distintas dentro de cada servicio. Una coincidencia de serie une su historial sin confirmar la identidad del episodio.',
    coverageNote:
      'La cobertura muestra todos los conjuntos seleccionados. Las fechas de la vista previa usan UTC. Las fechas del informe usan la zona horaria elegida.',
    weekdayActivity: 'Actividad por día de la semana',
    chartEmpty: 'No hay datos disponibles para este gráfico.',
    addFiles: 'Añadir archivos',
    uploadTitle: 'Subir tu historial de visualización',
    uploadHint: 'CSV de Netflix o ZIP de Prime Video',
    close: 'Cerrar',
    manageFiles: 'Gestionar archivos',
    analyzing: 'Analizando tu historial…',
    analysisFailed:
      'No se pudo completar el análisis. Reintenta o cancela el análisis pendiente.',
    importFailed:
      'No se pudo importar el archivo. Cancela la importación pendiente y vuelve a seleccionar el archivo.',
    history: 'Historial',
    filters: 'Filtros del informe',
    moreFilters: 'Más filtros',
    allTitles: 'Todos los títulos',
    films: 'Películas',
    mediaSplit: 'Películas y series',
    monthlyViewing: 'Actividad mensual',
    topGenres: 'Géneros más vistos',
    weekdayGenres: 'Géneros por día de la semana',
    originalLanguages: 'Idiomas originales',
    originalLanguageNote: 'El idioma original del título.',
    yearGenres: 'Géneros por año',
    genreOverlap: 'Una actividad puede pertenecer a varios géneros.',
    filteredPeriods:
      'Los recuentos cubren las fechas seleccionadas, incluidos los años parciales.',
    weekday: 'Día de la semana',
    viewingYear: 'Año de visualización',
    month: 'Mes',
    replaceFile: 'Reemplazar archivo',
    deleteData: 'Eliminar datos',
    deleteBody:
      'Se eliminarán el historial importado y los detalles de los títulos del servicio seleccionado.',
    aboutReport: 'Acerca de este informe',
    netflixGuide: 'Guía de exportación de Netflix',
    invalidFiles:
      'Selecciona como máximo un CSV de Netflix y un ZIP de Prime Video.'
  },
  fr: {
    heading: 'Historique de visionnage',
    allServices: 'Tous les services',
    provider: 'Service',
    timezone: 'Fuseau horaire',
    titleFilter: 'Rechercher un titre',
    exportCombined: 'Exporter le CSV filtré',
    profileLabel: 'Nom du profil',
    sourceCoverage: 'Couverture des sources',
    seconds: 'Secondes enregistrées',
    watchTime: 'Durée de lecture enregistrée',
    unknownDuration: 'Enregistrements de durée inconnue',
    exclusions: 'Exclus des totaux de visionnage',
    searches: 'Recherches',
    purchases: 'Achats',
    rentals: 'Locations',
    devices: 'Appareils',
    audioLanguages: 'Langues audio',
    subtitleLanguages: 'Langues des sous-titres',
    unsupported: 'Fichiers non pris en charge',
    datasets: 'Jeux de données',
    playbackDetails: 'Détails de lecture',
    watchEvents: 'Événements de lecture complémentaires',
    trailers: 'Bandes-annonces promotionnelles',
    sourceFile: 'Fichier source',
    sourceRow: 'Ligne source',
    unit: 'Unité de comptage',
    netflixUnit: 'Entrées d’activité',
    primeUnit: 'Enregistrements de lecture',
    profileType: 'Type de profil',
    completion: 'Achèvement',
    autoplay: 'Lecture automatique',
    deleted: 'Supprimé de l’historique',
    yes: 'Oui',
    no: 'Non',
    sourceNote:
      'Les totaux combinent les entrées Netflix et les lectures de contenu Prime avec une durée positive. Chaque service conserve son unité.',
    watchNote:
      'Les événements complémentaires, recherches, achats, bandes-annonces, promotions, entrées supprimées et durées nulles ou inconnues sont exclus des totaux.',
    timeNote:
      'Les horodatages Prime utilisent le fuseau choisi. Les dates Netflix restent identiques.',
    profileNote:
      'Prime indique des profils adultes ou enfants, sans identifiants de profils individuels.',
    runtimeNote:
      'La durée des métadonnées décrit le titre. Les secondes enregistrées décrivent la lecture. L’achèvement reste inconnu.',
    titleNote:
      'Seules les identités acceptées relient les services. Les titres non résolus gardent leur identité de service.',
    empty: 'Importez votre historique pour créer ce rapport.',
    confirmDeletePrime: 'Supprimer les données Prime Video',
    deletePrimeTitle: 'Supprimer toutes les données Prime Video ?',
    deletePrimeBody:
      'Les enregistrements, aperçus et résultats Prime seront supprimés de votre espace privé.',
    primeGuide: 'Guide d’exportation Amazon',
    next: 'Page suivante',
    previous: 'Page précédente',
    interval: 'Intervalle de lecture',
    content: 'Contenu',
    promotion: 'Promotion',
    trailer: 'Bande-annonce',
    live: 'Direct',
    adult: 'Adulte',
    child: 'Enfant',
    calendarDate: 'Date calendaire',
    timestamp: 'Horodatage UTC',
    unknownTitle: 'Titre indisponible',
    playbackEvidence: 'Achats avec preuve de lecture',
    recordedCoverage: 'Enregistrements de visionnage avec durée connue',
    episodeNote:
      'Le nombre d’épisodes utilise des identités de source distinctes dans chaque service. Une correspondance de série relie son historique sans confirmer l’identité de l’épisode.',
    coverageNote:
      'La couverture montre tous les jeux de données sélectionnés. Les dates de l’aperçu utilisent UTC. Les dates du rapport utilisent le fuseau choisi.',
    weekdayActivity: 'Activité par jour de la semaine',
    chartEmpty: 'Aucune donnée n’est disponible pour ce graphique.',
    addFiles: 'Ajouter des fichiers',
    uploadTitle: 'Importer votre historique',
    uploadHint: 'CSV Netflix ou ZIP Prime Video',
    close: 'Fermer',
    manageFiles: 'Gérer les fichiers',
    analyzing: 'Analyse de votre historique…',
    analysisFailed:
      'L’analyse n’a pas pu se terminer. Réessayez ou annulez l’analyse en cours.',
    importFailed:
      'Le fichier n’a pas pu être importé. Annulez l’importation en cours, puis sélectionnez à nouveau le fichier.',
    history: 'Historique',
    filters: 'Filtres du rapport',
    moreFilters: 'Plus de filtres',
    allTitles: 'Tous les titres',
    films: 'Films',
    mediaSplit: 'Films et séries',
    monthlyViewing: 'Activité mensuelle',
    topGenres: 'Genres les plus regardés',
    weekdayGenres: 'Genres par jour de la semaine',
    originalLanguages: 'Langues originales',
    originalLanguageNote: 'La langue originale du titre.',
    yearGenres: 'Genres par année',
    genreOverlap: 'Une activité peut appartenir à plusieurs genres.',
    filteredPeriods:
      'Les totaux couvrent les dates sélectionnées, y compris les années partielles.',
    weekday: 'Jour de la semaine',
    viewingYear: 'Année de visionnage',
    month: 'Mois',
    replaceFile: 'Remplacer le fichier',
    deleteData: 'Supprimer les données',
    deleteBody:
      'Cette action supprime l’historique importé et les détails des titres du service sélectionné.',
    aboutReport: 'À propos de ce rapport',
    netflixGuide: 'Guide d’exportation Netflix',
    invalidFiles:
      'Sélectionnez au maximum un CSV Netflix et un ZIP Prime Video.'
  },
  ru: {
    heading: 'История просмотров',
    allServices: 'Все сервисы',
    provider: 'Сервис',
    timezone: 'Часовой пояс',
    titleFilter: 'Найти название',
    exportCombined: 'Экспортировать CSV с фильтрами',
    profileLabel: 'Название профиля',
    sourceCoverage: 'Полнота исходных данных',
    seconds: 'Записанные секунды',
    watchTime: 'Записанное время просмотра',
    unknownDuration: 'Записи с неизвестной длительностью',
    exclusions: 'Исключено из общего потребления',
    searches: 'Поисковые запросы',
    purchases: 'Покупки',
    rentals: 'Аренда',
    devices: 'Устройства',
    audioLanguages: 'Языки звуковой дорожки',
    subtitleLanguages: 'Языки субтитров',
    unsupported: 'Неподдерживаемые файлы',
    datasets: 'Наборы данных',
    playbackDetails: 'Данные воспроизведения',
    watchEvents: 'Дополнительные события просмотра',
    trailers: 'Рекламные трейлеры',
    sourceFile: 'Исходный файл',
    sourceRow: 'Строка источника',
    unit: 'Единица подсчёта',
    netflixUnit: 'Записи активности',
    primeUnit: 'Записи воспроизведения',
    profileType: 'Тип профиля',
    completion: 'Завершённость просмотра',
    autoplay: 'Автовоспроизведение',
    deleted: 'Удалено из истории',
    yes: 'Да',
    no: 'Нет',
    sourceNote:
      'Общий итог объединяет записи Netflix и воспроизведения контента Prime с положительной длительностью. У каждого сервиса своя единица подсчёта.',
    watchNote:
      'Дополнительные события, поисковые запросы, покупки, трейлеры, реклама, удалённые записи и записи с нулевой или неизвестной длительностью исключены из итогов.',
    timeNote:
      'Время Prime отображается в выбранном часовом поясе. Даты Netflix остаются без изменений.',
    profileNote:
      'Prime указывает взрослый или детский тип профиля без идентификатора конкретного профиля.',
    runtimeNote:
      'Длительность из метаданных относится к произведению. Записанные секунды относятся к воспроизведению. Завершённость просмотра неизвестна.',
    titleNote:
      'Названия объединяются между сервисами только после подтверждённого сопоставления. Неопределённые названия сохраняют привязку к сервису.',
    empty: 'Импортируйте историю для создания отчёта.',
    confirmDeletePrime: 'Удалить данные Prime Video',
    deletePrimeTitle: 'Удалить все данные Prime Video?',
    deletePrimeBody:
      'Исходные записи Prime, результаты сопоставления и предварительные данные будут удалены из личного пространства.',
    primeGuide: 'Инструкция по выгрузке Amazon',
    next: 'Следующая страница',
    previous: 'Предыдущая страница',
    interval: 'Интервал воспроизведения',
    content: 'Контент',
    promotion: 'Реклама',
    trailer: 'Трейлер',
    live: 'Прямая трансляция',
    adult: 'Взрослый',
    child: 'Детский',
    calendarDate: 'Календарная дата',
    timestamp: 'Временная метка UTC',
    unknownTitle: 'Название недоступно',
    playbackEvidence: 'Покупки с данными о воспроизведении',
    recordedCoverage: 'Записи потребления с известной длительностью',
    episodeNote:
      'Количество эпизодов определяется по отдельным идентификаторам источника в каждом сервисе. Сопоставление сериала объединяет историю сериала, но не подтверждает идентичность эпизодов.',
    coverageNote:
      'Покрытие источника отражает все выбранные наборы данных. Даты предварительного просмотра указаны по UTC. Даты отчёта учитывают выбранный часовой пояс.',
    weekdayActivity: 'Активность по дням недели',
    chartEmpty: 'Для этого графика нет данных.',
    addFiles: 'Добавить файлы',
    uploadTitle: 'Загрузите историю просмотров',
    uploadHint: 'CSV Netflix или ZIP Prime Video',
    close: 'Закрыть',
    manageFiles: 'Управление файлами',
    analyzing: 'Анализ истории просмотров…',
    analysisFailed:
      'Не удалось завершить анализ. Повторите попытку или отмените текущий анализ.',
    importFailed:
      'Не удалось импортировать файл. Отмените текущий импорт и выберите файл ещё раз.',
    history: 'История',
    filters: 'Фильтры отчёта',
    moreFilters: 'Другие фильтры',
    allTitles: 'Все названия',
    films: 'Фильмы',
    mediaSplit: 'Фильмы и сериалы',
    monthlyViewing: 'Активность по месяцам',
    topGenres: 'Популярные жанры',
    weekdayGenres: 'Жанры по дням недели',
    originalLanguages: 'Языки оригинала',
    originalLanguageNote: 'Язык оригинала фильма или сериала.',
    yearGenres: 'Жанры по годам',
    genreOverlap: 'Один просмотр может относиться к нескольким жанрам.',
    filteredPeriods:
      'Количество просмотров относится к выбранным датам, включая неполные годы.',
    weekday: 'День недели',
    viewingYear: 'Год просмотра',
    month: 'Месяц',
    replaceFile: 'Заменить файл',
    deleteData: 'Удалить данные',
    deleteBody:
      'Будут удалены история просмотров и сведения о названиях выбранного сервиса.',
    aboutReport: 'Об этом отчёте',
    netflixGuide: 'Инструкция по экспорту Netflix',
    invalidFiles:
      'Выберите не более одного CSV Netflix и одного ZIP Prime Video.'
  }
};
